//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 10:26:14 PM CET 
//


package bier.webshop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="payment" type="{bier/webshop}payment"/>
 *         &lt;element ref="{bier/webshop}klantnaam"/>
 *         &lt;element ref="{bier/webshop}klantadres"/>
 *         &lt;element name="unique_payment_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "getPaymentResponse")
public class GetPaymentResponse {

    @XmlElement(required = true)
    protected Payment payment;
    @XmlElement(required = true)
    protected String klantnaam;
    @XmlElement(required = true)
    protected String klantadres;
    @XmlElement(name = "unique_payment_id", required = true)
    protected String uniquePaymentId;

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the klantnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlantnaam() {
        return klantnaam;
    }

    /**
     * Sets the value of the klantnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlantnaam(String value) {
        this.klantnaam = value;
    }

    /**
     * Gets the value of the klantadres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlantadres() {
        return klantadres;
    }

    /**
     * Sets the value of the klantadres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlantadres(String value) {
        this.klantadres = value;
    }

    /**
     * Gets the value of the uniquePaymentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniquePaymentId() {
        return uniquePaymentId;
    }

    /**
     * Sets the value of the uniquePaymentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniquePaymentId(String value) {
        this.uniquePaymentId = value;
    }

}
