//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 10:26:14 PM CET 
//


package bier.webshop;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bestelid" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element ref="{bier/webshop}klantnaam"/>
 *         &lt;element ref="{bier/webshop}klantadres"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bestelid",
    "klantnaam",
    "klantadres"
})
@XmlRootElement(name = "getPaymentRequest")
public class GetPaymentRequest {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger bestelid;
    @XmlElement(required = true)
    protected String klantnaam;
    @XmlElement(required = true)
    protected String klantadres;

    /**
     * Gets the value of the bestelid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBestelid() {
        return bestelid;
    }

    /**
     * Sets the value of the bestelid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBestelid(BigInteger value) {
        this.bestelid = value;
    }

    /**
     * Gets the value of the klantnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlantnaam() {
        return klantnaam;
    }

    /**
     * Sets the value of the klantnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlantnaam(String value) {
        this.klantnaam = value;
    }

    /**
     * Gets the value of the klantadres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlantadres() {
        return klantadres;
    }

    /**
     * Sets the value of the klantadres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlantadres(String value) {
        this.klantadres = value;
    }

}
