//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 10:26:14 PM CET 
//


package bier.webshop;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bier.webshop package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Klantadres_QNAME = new QName("bier/webshop", "klantadres");
    private final static QName _Klantnaam_QNAME = new QName("bier/webshop", "klantnaam");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bier.webshop
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPaymentRequest }
     * 
     */
    public GetPaymentRequest createGetPaymentRequest() {
        return new GetPaymentRequest();
    }

    /**
     * Create an instance of {@link GetPaymentResponse }
     * 
     */
    public GetPaymentResponse createGetPaymentResponse() {
        return new GetPaymentResponse();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Bestelling }
     * 
     */
    public Bestelling createBestelling() {
        return new Bestelling();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "bier/webshop", name = "klantadres")
    public JAXBElement<String> createKlantadres(String value) {
        return new JAXBElement<String>(_Klantadres_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "bier/webshop", name = "klantnaam")
    public JAXBElement<String> createKlantnaam(String value) {
        return new JAXBElement<String>(_Klantnaam_QNAME, String.class, null, value);
    }

}
